# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
      - name: create json file
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env_data.json"
          json: '{ "prod" :{ "API_URL": ${{ secrets.TODOIST_API_URL }}, "TOKEN": ${{ secrets.TOKEN }} }}'
          dir: 'todoistApp/'
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: cache maven 
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run a one-line script
        run: echo Starting the API testing!
      - name: test execution
        run: mvn test -Dkarate.env="prod"  -Dkarate.options="--tags @smoke"
