# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env_data.json"
          json: '{ "prod" :{ "API_URL": ${{ secrets.TODOIST_API_URL }}, "TOKEN": ${{ secrets.TODOIST_TOKEN }} }}'
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      # run smoke tests on All Browsers
      - name: Run Smoke tests
        run: mvn test -Dkarate.env="prod"  -Dkarate.options="--tags @smoke"
