# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  e2e-backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v3
      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: cache maven 
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: create json file
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "env_data.json"
          json: '{ "prod" :{ "API_URL": ${{ secrets.TODOIST_API_URL }}, "TOKEN": ${{ secrets.TOKEN }} }}'
      # create the Cucumber report folder to uploda the test result
      - name: Create dir
        run: |
          mkdir cucumber-html-reports
      - name: Run API Tests
        run: echo Starting the API testing!
      - name: test execution
        run: mvn test -Dkarate.env="prod"  -Dkarate.options="--tags @smoke"
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-report
          path: target/cucumber-html-reports
        if: always()
      ###### Commit Smoke Test status ######
      - name: Tests Passed
        if: ${{ success() }}
        # set the merge commit status check
        # using GitHub REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Smoke Tests",
            "state": "success",
            "description": "Smoke tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
      - name: Test Failed
        if: ${{ failure() }}
        # set the merge commit status check
        # using GitHub REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "Smoke Tests",
            "state": "failure",
            "description": "Smoke tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'
